import { Inter } from "next/font/google";
import "./globals.css";
import Navber1 from "@/Componet/Shared/Navber/Navber1";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
         
          
        
          <body >
            <div className="grid grid-cols-12">
              <div className="col-span-2 bg-[#3b3b3b] min-h-screen mt-5"><Navber1></Navber1></div>
              <div className="col-span-10"> {children}</div>
            </div>
           
            </body>

          
     
    </html>
  );
}
